services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: oficina_db
      POSTGRES_USER: carlos_dev
      POSTGRES_PASSWORD: senha_segura
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: auto_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/oficina_db
    depends_on:
      - db

  frontend:

    build: ./oficina-front
    container_name: auto_front
    ports:
      - "80:80"
    depends_on:
      - api